### ISSUE TITLE
feature request: rdate time on port 37

### ISSUE THREAD

**Issue by markstinson** [Montecri/GPSTimeServer#1]
Please consider implementing the rdate time protocol on port 37 (tcp &/or udp). 

Although NTP is better, rdate is "just good enough" in many situations. Due to its simplicity, it's perfect for most IoT and micro-devices. And being a standard, many legacy devices will support rdate over NTP.

It could also be helpful for folks needing a "just good enough" $20 device with a $12 GPS, $4 ESP32 or ESP-8266 & $4 RTC PCF8523.

very cool. cheers.

**Comment by Montecri** [comment]
Sorry, for some reason I didn't see your message before. I will work on it, looks really simple.

Would you be able to test once it is done and tell me the results?

Thank you!

**Comment by Montecri** [comment]
Hi @markstinson 

Just added RDATE support. Please take a look.

Regards,

- Cristiano
