### ISSUE TITLE
Wrong Time when bootup, for few seconds 

### ISSUE THREAD

**Issue by cheise** [Montecri/GPSTimeServer#6]
https://github.com/Montecri/GPSTimeServer/blob/b72ee8c58b891f41e3a836fae0de9ad482129ad0/src/main.cpp#L385

That is implausible, why greater than 3000. So there is wrong time for a few seconds when booting up!

`if (age < 1000)` is the better way, the issue is gone. ;)

cu

**Comment by Montecri** [comment]
Good catch! Will fix it today Thank you!

**Comment by Montecri** [comment]
Hi @mmarkin !

@cheise suggestion above makes sense. I've updated the main tree. Please feel free to do the same on the Dual Display tree.

Thanks & Regards,

- Cristiano

**Comment by Montecri** [comment]
Fixed as of today.
